[[blueprint.customizations.user]]
name = "bart"
password = "bart"
key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCx1kYpcCXTrxcC8KeLQS0V/rZ0BY1vn9e4J0LlIN1L/k6oL+i/CJL7TxvWGkHiWslNUKQflTH5c/K6dny0DCe9+gltlT5FLPKT8BIcmw/lP94vX7dC7lyCaqSr6SsI7lo4HWxHksUC9aqUq0sSDfv85b0SvMwnxSzWI1I3nINSmowSC8zvkvQD1j82nOgxkn36SisO5Nqu+AJ8jAHh41y9oWe8xb4FQxxHdUXy2bj9OziG0P/GWYJgXde0nmOgI3J4Cz8xTGKnlLL/WYbxh4gqErAroxxytIBOyPDtHk5CicMXxHfrqyQzbINXw6WreFkUx7uW5XG9qCRWc2J9/K9b4Hr6nMbFap/QddryXvtGgz4o54/4tpaMELyWXfBRasx3To5ebVKoNc0MqB8fwc85GIbBj7Feub5coel8pNA1Yx8oFNjL2z9wgmFPB5N7cJHul4RWJ8J3wIbOwT/QWdhjRgqCmCQZDpIeoZBCznpIVbKIxDwrX9Cqfor5zLFdSpc= bajoris@bajoris-mac"
groups = ["wheel"]
