apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: clone-build-push-run-
spec:
  pipelineRef:
    name: clone-build-push
  podTemplate:
    securityContext:
      fsGroup: 65532
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  - name: docker-credentials
    secret:
      secretName: rh-ee-bajoris-openshiftvirt-ocp-arrowolabs-pull-secret
  params:
  - name: repo-url
    value: https://github.com/BartJoris/bootc.git
  - name: repo-revision
    value: feature/pipeline
  - name: image-reference
    value: quay.io/rh_ee_bajoris/bootc:version